apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
  namespace: cap-bookstore
  labels:
    app: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: bookstore
        image: {YOUR_DOCKER_IMAGE_HERE}
        ports:
        - containerPort: 4004
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: bookstore-postgres-config
              key: NODE_ENV
        - name: CDS_REQUIRES_KIND
          valueFrom:
            configMapKeyRef:
              name: bookstore-postgres-config
              key: CDS_REQUIRES_KIND
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: bookstore-binding
              key: hostname
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: bookstore-binding
              key: port
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: bookstore-binding
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-binding
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: bookstore-binding
              key: dbname
        - name: POSTGRES_URI
          valueFrom:
            secretKeyRef:
              name: bookstore-binding
              key: uri
        - name: CDS_REQUIRES
          value: '{"db":{"kind":"postgres","credentials":{"url":"$(POSTGRES_URI)?sslmode=require","ssl":{"rejectUnauthorized":false}}}}'
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /odata/v4/catalog/$metadata
            port: 4004
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /odata/v4/catalog/$metadata
            port: 4004
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always