apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
  labels:
    app: bookstore
spec:
  selector:
    app: bookstore
  ports:
  - name: http
    port: 80
    targetPort: 4004
    protocol: TCP
  type: ClusterIP